import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { Providers } from "./provider";
import NavbarComponent from "@/components/navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#1E1E1E] overflow-x-hidden">
        <Providers>
          <NavbarComponent />
          {children}
          
        </Providers>
      </body>
    </html>
  );
}
